#!/bin/bash

GEN_PATH="$(pwd)/../"
VERSION=4.0.0

openapi-generator generate \
  -i https://api-gateway.sajari.com/v4/openapi.json  \
  -g csharp-netcore \
  -o $GEN_PATH \
  --artifact-version $VERSION \
  --http-user-agent "sajari-sdk-csharp-$VERSION" \
  --group-id Com.Sajari \
  --git-host "github.com/sajari" \
  --git-repo-id sdk-dotnet \
  --additional-properties packageName=Com.Sajari.Sdk \
  --additional-properties packageVersion=$VERSION
