/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Sajari.Sdk.Client.OpenAPIDateConverter;

namespace Com.Sajari.Sdk.Model
{
    /// <summary>
    /// BatchCreateSchemaFieldsResponseError
    /// </summary>
    [DataContract(Name = "BatchCreateSchemaFieldsResponseError")]
    public partial class BatchCreateSchemaFieldsResponseError : IEquatable<BatchCreateSchemaFieldsResponseError>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchCreateSchemaFieldsResponseError" /> class.
        /// </summary>
        /// <param name="index">Index of the schema field in &#x60;fields&#x60; that this error corresponds to..</param>
        /// <param name="status">status.</param>
        public BatchCreateSchemaFieldsResponseError(int index = default(int), Status status = default(Status))
        {
            this.Index = index;
            this.Status = status;
        }

        /// <summary>
        /// Index of the schema field in &#x60;fields&#x60; that this error corresponds to.
        /// </summary>
        /// <value>Index of the schema field in &#x60;fields&#x60; that this error corresponds to.</value>
        [DataMember(Name = "index", EmitDefaultValue = false)]
        public int Index { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public Status Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BatchCreateSchemaFieldsResponseError {\n");
            sb.Append("  Index: ").Append(Index).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BatchCreateSchemaFieldsResponseError);
        }

        /// <summary>
        /// Returns true if BatchCreateSchemaFieldsResponseError instances are equal
        /// </summary>
        /// <param name="input">Instance of BatchCreateSchemaFieldsResponseError to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BatchCreateSchemaFieldsResponseError input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Index == input.Index ||
                    this.Index.Equals(input.Index)
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Index.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
