/*
 * Search.io API
 *
 * Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@search.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Sajari.Sdk.Client.OpenAPIDateConverter;

namespace Com.Sajari.Sdk.Model
{
    /// <summary>
    /// BatchUpdateRecordsResponse
    /// </summary>
    [DataContract(Name = "BatchUpdateRecordsResponse")]
    public partial class BatchUpdateRecordsResponse : IEquatable<BatchUpdateRecordsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchUpdateRecordsResponse" /> class.
        /// </summary>
        /// <param name="errors">The errors that occurred..</param>
        /// <param name="records">A list of updated records..</param>
        public BatchUpdateRecordsResponse(List<BatchUpdateRecordsResponseError> errors = default(List<BatchUpdateRecordsResponseError>), List<BatchUpdateRecordsResponseRecord> records = default(List<BatchUpdateRecordsResponseRecord>))
        {
            this.Errors = errors;
            this.Records = records;
        }

        /// <summary>
        /// The errors that occurred.
        /// </summary>
        /// <value>The errors that occurred.</value>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        public List<BatchUpdateRecordsResponseError> Errors { get; set; }

        /// <summary>
        /// A list of updated records.
        /// </summary>
        /// <value>A list of updated records.</value>
        [DataMember(Name = "records", EmitDefaultValue = false)]
        public List<BatchUpdateRecordsResponseRecord> Records { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BatchUpdateRecordsResponse {\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  Records: ").Append(Records).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BatchUpdateRecordsResponse);
        }

        /// <summary>
        /// Returns true if BatchUpdateRecordsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of BatchUpdateRecordsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BatchUpdateRecordsResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Errors == input.Errors ||
                    this.Errors != null &&
                    input.Errors != null &&
                    this.Errors.SequenceEqual(input.Errors)
                ) && 
                (
                    this.Records == input.Records ||
                    this.Records != null &&
                    input.Records != null &&
                    this.Records.SequenceEqual(input.Records)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Errors != null)
                {
                    hashCode = (hashCode * 59) + this.Errors.GetHashCode();
                }
                if (this.Records != null)
                {
                    hashCode = (hashCode * 59) + this.Records.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
