/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Sajari.Sdk.Client.OpenAPIDateConverter;

namespace Com.Sajari.Sdk.Model
{
    /// <summary>
    /// BatchCreateSchemaFieldsResponse
    /// </summary>
    [DataContract(Name = "BatchCreateSchemaFieldsResponse")]
    public partial class BatchCreateSchemaFieldsResponse : IEquatable<BatchCreateSchemaFieldsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchCreateSchemaFieldsResponse" /> class.
        /// </summary>
        /// <param name="errors">Errors that occurred..</param>
        /// <param name="fields">Schema fields created..</param>
        public BatchCreateSchemaFieldsResponse(List<BatchCreateSchemaFieldsResponseError> errors = default(List<BatchCreateSchemaFieldsResponseError>), List<SchemaField> fields = default(List<SchemaField>))
        {
            this.Errors = errors;
            this.Fields = fields;
        }

        /// <summary>
        /// Errors that occurred.
        /// </summary>
        /// <value>Errors that occurred.</value>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        public List<BatchCreateSchemaFieldsResponseError> Errors { get; set; }

        /// <summary>
        /// Schema fields created.
        /// </summary>
        /// <value>Schema fields created.</value>
        [DataMember(Name = "fields", EmitDefaultValue = false)]
        public List<SchemaField> Fields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BatchCreateSchemaFieldsResponse {\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BatchCreateSchemaFieldsResponse);
        }

        /// <summary>
        /// Returns true if BatchCreateSchemaFieldsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of BatchCreateSchemaFieldsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BatchCreateSchemaFieldsResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Errors == input.Errors ||
                    this.Errors != null &&
                    input.Errors != null &&
                    this.Errors.SequenceEqual(input.Errors)
                ) && 
                (
                    this.Fields == input.Fields ||
                    this.Fields != null &&
                    input.Fields != null &&
                    this.Fields.SequenceEqual(input.Fields)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Errors != null)
                    hashCode = hashCode * 59 + this.Errors.GetHashCode();
                if (this.Fields != null)
                    hashCode = hashCode * 59 + this.Fields.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
