/*
 * Search.io API
 *
 * Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@search.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Sajari.Sdk.Client.OpenAPIDateConverter;

namespace Com.Sajari.Sdk.Model
{
    /// <summary>
    ///  - TYPE_UNSPECIFIED: Type not specified.  - WEBSITE: The type for website collections.  - SHOPIFY: The type for the collection backing a Shopify account.  - CUSTOM: The legacy custom type.
    /// </summary>
    /// <value> - TYPE_UNSPECIFIED: Type not specified.  - WEBSITE: The type for website collections.  - SHOPIFY: The type for the collection backing a Shopify account.  - CUSTOM: The legacy custom type.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CollectionType
    {
        /// <summary>
        /// Enum TYPEUNSPECIFIED for value: TYPE_UNSPECIFIED
        /// </summary>
        [EnumMember(Value = "TYPE_UNSPECIFIED")]
        TYPEUNSPECIFIED = 1,

        /// <summary>
        /// Enum WEBSITE for value: WEBSITE
        /// </summary>
        [EnumMember(Value = "WEBSITE")]
        WEBSITE = 2,

        /// <summary>
        /// Enum SHOPIFY for value: SHOPIFY
        /// </summary>
        [EnumMember(Value = "SHOPIFY")]
        SHOPIFY = 3,

        /// <summary>
        /// Enum CUSTOM for value: CUSTOM
        /// </summary>
        [EnumMember(Value = "CUSTOM")]
        CUSTOM = 4

    }

}
