/*
 * Search.io API
 *
 * Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@search.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Sajari.Sdk.Client.OpenAPIDateConverter;

namespace Com.Sajari.Sdk.Model
{
    /// <summary>
    ///  - PIN: The pin applies regardless of whether the pinned item is in the underlying result set of the search.  This has the net effect that a search result can be surfaced even if it was not originally a part of the search result set.  - PROMOTE: The pin only applies if the pinned item is in the underlying result set of the search.
    /// </summary>
    /// <value> - PIN: The pin applies regardless of whether the pinned item is in the underlying result set of the search.  This has the net effect that a search result can be surfaced even if it was not originally a part of the search result set.  - PROMOTE: The pin only applies if the pinned item is in the underlying result set of the search.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PromotionPinMode
    {
        /// <summary>
        /// Enum PIN for value: PIN
        /// </summary>
        [EnumMember(Value = "PIN")]
        PIN = 1,

        /// <summary>
        /// Enum PROMOTE for value: PROMOTE
        /// </summary>
        [EnumMember(Value = "PROMOTE")]
        PROMOTE = 2

    }

}
