/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Sajari.Sdk.Client.OpenAPIDateConverter;

namespace Com.Sajari.Sdk.Model
{
    /// <summary>
    /// QueryResult
    /// </summary>
    [DataContract(Name = "QueryResult")]
    public partial class QueryResult : IEquatable<QueryResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryResult" /> class.
        /// </summary>
        /// <param name="indexScore">Index score..</param>
        /// <param name="record">An object made up of field-value pairs that contains the record data..</param>
        /// <param name="score">The normalized score attributed to this record. Combines the index score and feature score..</param>
        /// <param name="token">token.</param>
        public QueryResult(double indexScore = default(double), Object record = default(Object), double score = default(double), QueryResultToken token = default(QueryResultToken))
        {
            this.IndexScore = indexScore;
            this.Record = record;
            this.Score = score;
            this.Token = token;
        }

        /// <summary>
        /// Index score.
        /// </summary>
        /// <value>Index score.</value>
        [DataMember(Name = "index_score", EmitDefaultValue = false)]
        public double IndexScore { get; set; }

        /// <summary>
        /// An object made up of field-value pairs that contains the record data.
        /// </summary>
        /// <value>An object made up of field-value pairs that contains the record data.</value>
        [DataMember(Name = "record", EmitDefaultValue = false)]
        public Object Record { get; set; }

        /// <summary>
        /// The normalized score attributed to this record. Combines the index score and feature score.
        /// </summary>
        /// <value>The normalized score attributed to this record. Combines the index score and feature score.</value>
        [DataMember(Name = "score", EmitDefaultValue = false)]
        public double Score { get; set; }

        /// <summary>
        /// Gets or Sets Token
        /// </summary>
        [DataMember(Name = "token", EmitDefaultValue = false)]
        public QueryResultToken Token { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QueryResult {\n");
            sb.Append("  IndexScore: ").Append(IndexScore).Append("\n");
            sb.Append("  Record: ").Append(Record).Append("\n");
            sb.Append("  Score: ").Append(Score).Append("\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QueryResult);
        }

        /// <summary>
        /// Returns true if QueryResult instances are equal
        /// </summary>
        /// <param name="input">Instance of QueryResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QueryResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IndexScore == input.IndexScore ||
                    this.IndexScore.Equals(input.IndexScore)
                ) && 
                (
                    this.Record == input.Record ||
                    (this.Record != null &&
                    this.Record.Equals(input.Record))
                ) && 
                (
                    this.Score == input.Score ||
                    this.Score.Equals(input.Score)
                ) && 
                (
                    this.Token == input.Token ||
                    (this.Token != null &&
                    this.Token.Equals(input.Token))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.IndexScore.GetHashCode();
                if (this.Record != null)
                    hashCode = hashCode * 59 + this.Record.GetHashCode();
                hashCode = hashCode * 59 + this.Score.GetHashCode();
                if (this.Token != null)
                    hashCode = hashCode * 59 + this.Token.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
