/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Sajari.Sdk.Client.OpenAPIDateConverter;

namespace Com.Sajari.Sdk.Model
{
    /// <summary>
    /// SetDefaultVersionRequest
    /// </summary>
    [DataContract(Name = "SetDefaultVersionRequest")]
    public partial class SetDefaultVersionRequest : IEquatable<SetDefaultVersionRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetDefaultVersionRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SetDefaultVersionRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SetDefaultVersionRequest" /> class.
        /// </summary>
        /// <param name="version">The version to use as a default for this pipeline, e.g. &#x60;42&#x60;. (required).</param>
        public SetDefaultVersionRequest(string version = default(string))
        {
            // to ensure "version" is required (not null)
            if (version == null) {
                throw new ArgumentNullException("version is a required property for SetDefaultVersionRequest and cannot be null");
            }
            this._Version = version;
        }

        /// <summary>
        /// The version to use as a default for this pipeline, e.g. &#x60;42&#x60;.
        /// </summary>
        /// <value>The version to use as a default for this pipeline, e.g. &#x60;42&#x60;.</value>
        [DataMember(Name = "version", IsRequired = true, EmitDefaultValue = false)]
        public string _Version { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SetDefaultVersionRequest {\n");
            sb.Append("  _Version: ").Append(_Version).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SetDefaultVersionRequest);
        }

        /// <summary>
        /// Returns true if SetDefaultVersionRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SetDefaultVersionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SetDefaultVersionRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._Version == input._Version ||
                    (this._Version != null &&
                    this._Version.Equals(input._Version))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._Version != null)
                    hashCode = hashCode * 59 + this._Version.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
