/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Com.Sajari.Sdk.Client;
using Com.Sajari.Sdk.Api;
// uncomment below to import models
//using Com.Sajari.Sdk.Model;

namespace Com.Sajari.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing RecordsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RecordsApiTests : IDisposable
    {
        private RecordsApi instance;

        public RecordsApiTests()
        {
            instance = new RecordsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RecordsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' RecordsApi
            //Assert.IsType<RecordsApi>(instance);
        }

        /// <summary>
        /// Test BatchUpsertRecords
        /// </summary>
        [Fact]
        public void BatchUpsertRecordsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string collectionId = null;
            //BatchUpsertRecordsRequest batchUpsertRecordsRequest = null;
            //var response = instance.BatchUpsertRecords(collectionId, batchUpsertRecordsRequest);
            //Assert.IsType<BatchUpsertRecordsResponse>(response);
        }

        /// <summary>
        /// Test DeleteRecord
        /// </summary>
        [Fact]
        public void DeleteRecordTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string collectionId = null;
            //DeleteRecordRequest deleteRecordRequest = null;
            //var response = instance.DeleteRecord(collectionId, deleteRecordRequest);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test GetRecord
        /// </summary>
        [Fact]
        public void GetRecordTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string collectionId = null;
            //GetRecordRequest getRecordRequest = null;
            //var response = instance.GetRecord(collectionId, getRecordRequest);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test UpsertRecord
        /// </summary>
        [Fact]
        public void UpsertRecordTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string collectionId = null;
            //UpsertRecordRequest upsertRecordRequest = null;
            //var response = instance.UpsertRecord(collectionId, upsertRecordRequest);
            //Assert.IsType<UpsertRecordResponse>(response);
        }
    }
}
