/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Sajari.Sdk.Api;
using Com.Sajari.Sdk.Model;
using Com.Sajari.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Sajari.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing BatchCreateSchemaFieldsResponseError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchCreateSchemaFieldsResponseErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchCreateSchemaFieldsResponseError
        //private BatchCreateSchemaFieldsResponseError instance;

        public BatchCreateSchemaFieldsResponseErrorTests()
        {
            // TODO uncomment below to create an instance of BatchCreateSchemaFieldsResponseError
            //instance = new BatchCreateSchemaFieldsResponseError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchCreateSchemaFieldsResponseError
        /// </summary>
        [Fact]
        public void BatchCreateSchemaFieldsResponseErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchCreateSchemaFieldsResponseError
            //Assert.IsType<BatchCreateSchemaFieldsResponseError>(instance);
        }


        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
