/*
 * Search.io API
 *
 * Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@search.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Sajari.Sdk.Api;
using Com.Sajari.Sdk.Model;
using Com.Sajari.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Sajari.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing BatchUpdateRecordsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchUpdateRecordsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchUpdateRecordsRequest
        //private BatchUpdateRecordsRequest instance;

        public BatchUpdateRecordsRequestTests()
        {
            // TODO uncomment below to create an instance of BatchUpdateRecordsRequest
            //instance = new BatchUpdateRecordsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchUpdateRecordsRequest
        /// </summary>
        [Fact]
        public void BatchUpdateRecordsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchUpdateRecordsRequest
            //Assert.IsType<BatchUpdateRecordsRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Requests'
        /// </summary>
        [Fact]
        public void RequestsTest()
        {
            // TODO unit test for the property 'Requests'
        }
        /// <summary>
        /// Test the property 'UpdateMask'
        /// </summary>
        [Fact]
        public void UpdateMaskTest()
        {
            // TODO unit test for the property 'UpdateMask'
        }

    }

}
