/*
 * Search.io API
 *
 * Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@search.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Sajari.Sdk.Api;
using Com.Sajari.Sdk.Model;
using Com.Sajari.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Sajari.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ExperimentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExperimentRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExperimentRequest
        //private ExperimentRequest instance;

        public ExperimentRequestTests()
        {
            // TODO uncomment below to create an instance of ExperimentRequest
            //instance = new ExperimentRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExperimentRequest
        /// </summary>
        [Fact]
        public void ExperimentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExperimentRequest
            //Assert.IsType<ExperimentRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CustomPipeline'
        /// </summary>
        [Fact]
        public void CustomPipelineTest()
        {
            // TODO unit test for the property 'CustomPipeline'
        }
        /// <summary>
        /// Test the property 'Pipeline'
        /// </summary>
        [Fact]
        public void PipelineTest()
        {
            // TODO unit test for the property 'Pipeline'
        }
        /// <summary>
        /// Test the property 'Promotions'
        /// </summary>
        [Fact]
        public void PromotionsTest()
        {
            // TODO unit test for the property 'Promotions'
        }
        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Fact]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }

    }

}
