/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Sajari.Sdk.Api;
using Com.Sajari.Sdk.Model;
using Com.Sajari.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Sajari.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ListPipelinesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListPipelinesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListPipelinesResponse
        //private ListPipelinesResponse instance;

        public ListPipelinesResponseTests()
        {
            // TODO uncomment below to create an instance of ListPipelinesResponse
            //instance = new ListPipelinesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListPipelinesResponse
        /// </summary>
        [Fact]
        public void ListPipelinesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListPipelinesResponse
            //Assert.IsType<ListPipelinesResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Pipelines'
        /// </summary>
        [Fact]
        public void PipelinesTest()
        {
            // TODO unit test for the property 'Pipelines'
        }
        /// <summary>
        /// Test the property 'NextPageToken'
        /// </summary>
        [Fact]
        public void NextPageTokenTest()
        {
            // TODO unit test for the property 'NextPageToken'
        }

    }

}
