/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Sajari.Sdk.Api;
using Com.Sajari.Sdk.Model;
using Com.Sajari.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Sajari.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PipelineStepParamBinding
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PipelineStepParamBindingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PipelineStepParamBinding
        //private PipelineStepParamBinding instance;

        public PipelineStepParamBindingTests()
        {
            // TODO uncomment below to create an instance of PipelineStepParamBinding
            //instance = new PipelineStepParamBinding();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PipelineStepParamBinding
        /// </summary>
        [Fact]
        public void PipelineStepParamBindingInstanceTest()
        {
            // TODO uncomment below to test "IsType" PipelineStepParamBinding
            //Assert.IsType<PipelineStepParamBinding>(instance);
        }


        /// <summary>
        /// Test the property 'Bind'
        /// </summary>
        [Fact]
        public void BindTest()
        {
            // TODO unit test for the property 'Bind'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DefaultValue'
        /// </summary>
        [Fact]
        public void DefaultValueTest()
        {
            // TODO unit test for the property 'DefaultValue'
        }
        /// <summary>
        /// Test the property 'Constant'
        /// </summary>
        [Fact]
        public void ConstantTest()
        {
            // TODO unit test for the property 'Constant'
        }

    }

}
