/*
 * Search.io API
 *
 * Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@search.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Sajari.Sdk.Api;
using Com.Sajari.Sdk.Model;
using Com.Sajari.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Sajari.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PromotionFilterCondition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PromotionFilterConditionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PromotionFilterCondition
        //private PromotionFilterCondition instance;

        public PromotionFilterConditionTests()
        {
            // TODO uncomment below to create an instance of PromotionFilterCondition
            //instance = new PromotionFilterCondition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PromotionFilterCondition
        /// </summary>
        [Fact]
        public void PromotionFilterConditionInstanceTest()
        {
            // TODO uncomment below to test "IsType" PromotionFilterCondition
            //Assert.IsType<PromotionFilterCondition>(instance);
        }


        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

    }

}
