/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Sajari.Sdk.Api;
using Com.Sajari.Sdk.Model;
using Com.Sajari.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Sajari.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ProtobufNullValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProtobufNullValueTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProtobufNullValue
        //private ProtobufNullValue instance;

        public ProtobufNullValueTests()
        {
            // TODO uncomment below to create an instance of ProtobufNullValue
            //instance = new ProtobufNullValue();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProtobufNullValue
        /// </summary>
        [Fact]
        public void ProtobufNullValueInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProtobufNullValue
            //Assert.IsType<ProtobufNullValue>(instance);
        }



    }

}
