/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Sajari.Sdk.Api;
using Com.Sajari.Sdk.Model;
using Com.Sajari.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Sajari.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ProtobufAny
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProtobufAnyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProtobufAny
        //private ProtobufAny instance;

        public ProtobufAnyTests()
        {
            // TODO uncomment below to create an instance of ProtobufAny
            //instance = new ProtobufAny();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProtobufAny
        /// </summary>
        [Fact]
        public void ProtobufAnyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProtobufAny
            //Assert.IsType<ProtobufAny>(instance);
        }


        /// <summary>
        /// Test the property 'TypeUrl'
        /// </summary>
        [Fact]
        public void TypeUrlTest()
        {
            // TODO unit test for the property 'TypeUrl'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
