/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Sajari.Sdk.Api;
using Com.Sajari.Sdk.Model;
using Com.Sajari.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Sajari.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing QueryAggregateResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QueryAggregateResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QueryAggregateResult
        //private QueryAggregateResult instance;

        public QueryAggregateResultTests()
        {
            // TODO uncomment below to create an instance of QueryAggregateResult
            //instance = new QueryAggregateResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QueryAggregateResult
        /// </summary>
        [Fact]
        public void QueryAggregateResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" QueryAggregateResult
            //Assert.IsType<QueryAggregateResult>(instance);
        }


        /// <summary>
        /// Test the property 'Metric'
        /// </summary>
        [Fact]
        public void MetricTest()
        {
            // TODO unit test for the property 'Metric'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Buckets'
        /// </summary>
        [Fact]
        public void BucketsTest()
        {
            // TODO unit test for the property 'Buckets'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Analysis'
        /// </summary>
        [Fact]
        public void AnalysisTest()
        {
            // TODO unit test for the property 'Analysis'
        }

    }

}
