/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Sajari.Sdk.Api;
using Com.Sajari.Sdk.Model;
using Com.Sajari.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Sajari.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing QueryCollectionResponsePipeline
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QueryCollectionResponsePipelineTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QueryCollectionResponsePipeline
        //private QueryCollectionResponsePipeline instance;

        public QueryCollectionResponsePipelineTests()
        {
            // TODO uncomment below to create an instance of QueryCollectionResponsePipeline
            //instance = new QueryCollectionResponsePipeline();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QueryCollectionResponsePipeline
        /// </summary>
        [Fact]
        public void QueryCollectionResponsePipelineInstanceTest()
        {
            // TODO uncomment below to test "IsType" QueryCollectionResponsePipeline
            //Assert.IsType<QueryCollectionResponsePipeline>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Fact]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }

    }

}
