/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@sajari.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Sajari.Sdk.Api;
using Com.Sajari.Sdk.Model;
using Com.Sajari.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Sajari.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SchemaField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SchemaFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SchemaField
        //private SchemaField instance;

        public SchemaFieldTests()
        {
            // TODO uncomment below to create an instance of SchemaField
            //instance = new SchemaField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SchemaField
        /// </summary>
        [Fact]
        public void SchemaFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" SchemaField
            //Assert.IsType<SchemaField>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }
        /// <summary>
        /// Test the property 'Array'
        /// </summary>
        [Fact]
        public void ArrayTest()
        {
            // TODO unit test for the property 'Array'
        }
        /// <summary>
        /// Test the property 'ArrayLength'
        /// </summary>
        [Fact]
        public void ArrayLengthTest()
        {
            // TODO unit test for the property 'ArrayLength'
        }

    }

}
